### ISSUE TITLE
prova problema: spazi nel login

### ISSUE THREAD

**Issue by ftrole** [SimoDR/PAOProject#3]
trovare un modo per ignorare gli spazi digitati dopo la parola sul login

**Comment by antobaddo** [comment]
ieri avevo visto che il tuo "modello preferito" avesse creato un username con gli spazi

**Comment by ftrole** [comment]
ah ok allora il login è spazio-sensitive 👍

**Comment by SimoDR** [comment]
Prova issue
Sì direi anch'io che è spazio sensitive, nella realtà è così
